name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push React Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kawal285/docker-react-mysqlfile-react:latest

      - name: Build and push MySQL Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.mysql
          push: true
          tags: kawal285/docker-react-mysqlfile-mysql:latest
